# THIS IS THE CONFIGURATION FILE FOR GRIDDING
# YOU CAN SET UP THE RESOLUTION FOR THE GRID, DAYS TO PROCESS IN BATCH, AND THE BOUNDING BOX
grid_size: 0.1
min_lon: -180
max_lon: 180
min_lat: -90
max_lat: 90
num_cores: 4
start_date: "20240101"
end_date: "20240131"
data_export_path: "."